build:
  version: "1.1"

orders:
  message: "Welcome to Payments Microservice"
  contactDetails:
    name: "GKR"
    email: "gkr@gmail.com"
spring:
  application:
    name: payments-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: springstudent
    password: springstudent

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "Payments"
    description: "Payments Microservice"
    version: "1.0"
