build:
  version: "1.1"

orders:
  message: "Welcome to Products Microservice"
  contactDetails:
    name: "GKR"
    email: "gkr@gmail.com"
  
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: springstudent
    password: springstudent

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: "product-service"
    description: "Product microservice"
    version: "1.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
